branch-defaults:
  default:
    environment: eb-test-2-env
    group_suffix: null
global:
  application_name: eb-test-2
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
