branch-defaults:
  default:
    environment: eb-simple-test-prod
    group_suffix: null
  develop:
    environment: eb-simple-test-dev
    group_suffix: null
  master:
    environment: eb-simple-test-prod
environment-defaults:
  eb-test-4-dev:
    branch: null
    repository: null
global:
  application_name: eb-simple-test
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
